name: Deploy to Server

on:
  push:
    branches:
      - PasskeyWork

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.17.0'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to server
        env:
          HOST: ${{ secrets.DROPLET_IP }}
          USERNAME: ${{ secrets.SSH_USERNAME }}
          PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          echo "Username: $USERNAME"
          echo "Host: $HOST"
          echo "Attempting SSH connection..."
          sshpass -p "$PASSWORD" ssh -v -o StrictHostKeyChecking=no $USERNAME@$HOST << 'EOF'
            echo "Connection successful!"
            cd ~/QuilRocks
            git pull origin PasskeyWork
            npm ci
            npm run build
            pm2 restart quil-rocks-staging || pm2 start npm --name "quil-rocks-staging" -- run start
          EOF