name: Deploy to Server

on:
  push:
    branches:
      - main  # Takip etmek istediğiniz branch'i belirtin

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.17.0'  # Node.js sürümünü 18.17.0 veya daha yeni bir sürüm olarak ayarlayın

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to server
        env:
          HOST: ${{ secrets.DROPLET_IP }}
          USERNAME: ${{ secrets.SSH_USERNAME }}
          PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          sshpass -p ${{ secrets.PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} << EOF
            cd ~/QuilRocks
            git pull origin main
            npm install
            npm run build
            pm2 restart quil-rocks
          EOF
