name: Deploy to Server

on:
  push:
    branches:
      - development  # Takip etmek istediğiniz branch'i belirtin

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.17.0'  # Node.js sürümünü 18.17.0 veya daha yeni bir sürüm olarak ayarlayın

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to server
        env:
          HOST: ${{ secrets.DROPLET_IP }}
          USERNAME: ${{ secrets.SSH_USERNAME }}
          PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          echo "Username: $USERNAME"
          echo "Host: $HOST"
          echo "Attempting SSH connection..."
          sshpass -p "$PASSWORD" ssh -v -o StrictHostKeyChecking=no $USERNAME@$HOST << 'EOF'
            echo "Connection successful!"
            cd ~/QuilRocks
            git pull origin development
            npm install
            npm run build
            pm2 restart quil-rocks-staging
          EOF
